language: cpp
dist: xenial
compiler: gcc

install:
 # shared install
 - wget https://raw.githubusercontent.com/richelbilderbeek/correct_cpp/master/shared/install
 - chmod +x install
 # Use 'apt install' these days
 - sudo ./install
 - g++ -v

script: 
 # Test that it compiles in debug mode
 - echo "Debug mode"
 - g++ main.cpp
 - ./a.out
 - cppcheck --quiet --enable=all --error-exitcode=1 . 
 
