language: cpp
dist: xenial
compiler: gcc

install:
 - sudo ./setup/install
 - g++ -v

script: 
 # Test that it compiles in debug mode
 - echo "Debug mode"
 - g++ main.cpp
 - ./a.out
 - cppcheck --quiet --enable=all --error-exitcode=1 . 
 
