language: cpp
dist: xenial
compiler: gcc

install:
 - chmod +x ./setup/install
 - sudo ./setup/install
 #- sudo apt install -qq cppcheck
 - g++ -v

script: 
 # Test that it compiles in debug mode
 - echo "Debug mode"
 - g++ main.cpp
 - ./a.out
 #- cppcheck --quiet --enable=all --error-exitcode=1 . 
 - ./setup/do_oclint
 - ./check_doc
 
