#!/bin/bash

# Codecov
sudo pip install codecov

# OCLint
chmod +x ./setup/install_oclint 
./setup/install_oclint

# cppcheck
# sudo apt install -qq cppcheck

# Doxygen
sudo apt install -qq doxygen graphviz

# OCLint
chmod +x ./setup/do_oclint

# Codecov
chmod +x ./setup/get_code_cov

# Check guidelines
chmod +x ./setup/check_cpp_core_guidelines

# Check documentation
chmod +x ./setup/check_doc

